# Site settings
title: Initium Appraiser
email: jeff.fredrickson@gmail.com
description: >
  Evaluate the value of Initium items.
baseurl: ""
url: "http://initium-appraiser.github.io"

# Build settings
markdown: kramdown
